source 'https://rubygems.org'

# Padrino supports Ruby version 2.2.2 and later
# ruby '2.4.1'

gem 'activerecord', '>= 3.1', require: 'active_record'
gem 'activesupport', '>= 3.1'
gem 'bcrypt'
gem 'factory_bot'
gem 'faye-websocket'
gem 'haml'
gem 'oj'
gem 'padrino', github: 'padrino/padrino-framework'
gem 'padrino-sprockets', require: 'padrino/sprockets'
gem 'padrino-websockets'
gem 'pry'
gem 'puma'
gem 'rack-test', require: 'rack/test', group: 'test'
gem 'rake'
gem 'rspec', group: 'test'
gem 'sass'
gem 'sqlite3'
gem 'uglifier', '2.1.1'
gem 'yui-compressor', '0.9.6'

